name: Angular Test cases

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      run: cd career-service-app-client && npm install
    - name: Lint
      run: cd career-service-app-client && npm run lint
    - name: Test
      run: cd career-service-app-client && npm test -- --configuration=ci