name: Spring Boot JUnit Test cases

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        run:  cd career-service-backend && mvn --batch-mode -DskipTests package

      - name: Test
        run:  cd career-service-backend && mvn --batch-mode -Dmaven.test.failure.ignore=true test